<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>

  <ItemGroup Label="API">
    <PackageVersion Include="Microsoft.AspNetCore.OpenApi" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11" />
    <PackageVersion Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.11" />
    <PackageVersion Include="Scalar.AspNetCore" Version="2.17.2" />
  </ItemGroup>

  <!-- Application: solo paquetes MIT/Apache 2.0 (ADR 0014) -->
  <ItemGroup Label="Application">
    <PackageVersion Include="FluentValidation" Version="11.11.0" />
    <PackageVersion Include="FluentValidation.DependencyInjectionExtensions" Version="11.11.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup Label="Infrastructure / Persistence">
    <PackageVersion Include="Microsoft.EntityFrameworkCore" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.InMemory" Version="10.0.11" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Tools" Version="10.0.11" />
    <PackageVersion Include="System.IdentityModel.Tokens.Jwt" Version="8.5.0" />
    <PackageVersion Include="BCrypt.Net-Next" Version="4.0.3" />
  </ItemGroup>

  <ItemGroup Label="Infrastructure / DI">
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Options" Version="10.0.11" />
  </ItemGroup>

  <ItemGroup Label="Testing — shared">
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.13.0" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.0.2" />
    <PackageVersion Include="FluentAssertions" Version="6.12.2" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
  </ItemGroup>

  <ItemGroup Label="Testing — Architecture">
    <PackageVersion Include="TngTech.ArchUnitNET.xUnit" Version="0.11.3" />
  </ItemGroup>
</Project>
