<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="TngTech.ArchUnitNET.xUnit" />
    <PackageReference Include="coverlet.collector" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Pos.Domain\Pos.Domain.csproj" />
    <ProjectReference Include="..\..\src\Pos.Application\Pos.Application.csproj" />
    <ProjectReference Include="..\..\src\Pos.Infrastructure\Pos.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\Pos.Api\Pos.Api.csproj" />
  </ItemGroup>

</Project>